server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    # 설정 서버에서 설정을 필터링하는데 사용하는 어플리케이션의 이름
    name: catalog-service
  config:
    # 가능하면 컨피그서버에서 설정데이터를 가져온다.
    # 서비스가 시작될때 설정 서버가 실행되고 있지 않을 경우 어플리케이션의 로드를 중지하지 않음.
    import: "optional:configserver:"
  cloud:
    config:
      # 설정서버의 URL
      uri: http://localhost:8888
      # 설정 서버에 연결될 때까지 기다리는 시간(ms)
      request-connect-timeout: 5000
      # 설정 서버에서 데이터를 읽을 때까지 기다리는 시간(ms)
      request-read-timeout: 5000
      # 설정 서버 연결 실패를 치명적 오류로 인식(프로덕션 환경에서는 true로 설정할 것)
      fail-fast: false
      # 설정 서버와의 연결 실패시 재시도 패턴(최종적 실패로 판단하기 전에 연결을 몇 번 더 시도하도록 설정)
      retry:
        # 최대 시도 횟수
        max-attempts: 6
        # 최초 재시도 지연 시간(ms)
        initial-interval: 1000
        # 재시도 지연 최대 시간(ms)
        max-interval: 2000
        # 지연시간 계산 승수
        multiplier: 1.1
  # 주어진 데이터베이스에 엑세스 권한을 가지고 있는 유저의 자격증명과 연결을 원하는 데이터베이스에 대한 JDBC URL
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    # 성능과 복원력에 영향을 미치는 커넥션 풀에 대한 설정
    hikari:
      # 커넥션 풀에서 객체를 얻기 위해 기다려야하는 최대 시간(ms)
      connection-timeout: 2000
      # Hikari CP가 풀에 최대한으로 유지할 수 있는 연결 객체의 수
      maximum-pool-size: 5
  # 어플리케이션 로드 시 DB에 테이블 생성 명시
  # flyway사용으로 미사용
#  sql:
#    init:
#      mode: always

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        # HTTP를 통해 /actuator/refresh 엔드포인트를 노출(http://host:port/actuator/refresh POST 호출)
        include: refresh

polar:
  greeting: Welcome to the local book catalog!