DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
    ID                  BIGSERIAL PRIMARY KEY NOT NULL,
    AUTHOR              VARCHAR(255) NOT NULL,
    ISBN                VARCHAR(255) UNIQUE NOT NULL,
    PRICE               FLOAT8 NOT NULL,
    TITLE               VARCHAR(255) NOT NULL,
    CREATED_DATE        TIMESTAMP NOT NULL,
    LAST_MODIFIED_DATE  TIMESTAMP NOT NULL,
    VERSION             INTEGER NOT NULL
);